In [ ]:
a=10
a

10

In [ ]:
a=10
b=20
print(a)
b


10


20

In [ ]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
import numpy as np
arr=np.array(a)
arr


array([1, 2, 3, 4, 5])

In [ ]:
print(np.min(arr))

1


In [ ]:
print(np.max(arr))

5


In [ ]:
print(np.mean(arr))

3.0


In [ ]:
print(np.median(arr))

3.0


In [ ]:
b=np.zeros([4,5])
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
g=np.ones([3,3])
g


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
r=np.random.rand(5,3,7)
r

array([[[0.51484653, 0.82843593, 0.21488053, 0.55388182, 0.61900034,
         0.43403088, 0.32027184],
        [0.91411833, 0.45765139, 0.63507622, 0.66463136, 0.01185731,
         0.07729987, 0.2853395 ],
        [0.95797588, 0.53327192, 0.84708035, 0.44332907, 0.53876711,
         0.74982271, 0.74220782]],

       [[0.34028499, 0.71485827, 0.82956021, 0.40666999, 0.23796802,
         0.37747737, 0.9166424 ],
        [0.21073852, 0.5282769 , 0.5914361 , 0.50778223, 0.14697215,
         0.80923989, 0.82692903],
        [0.14587576, 0.85257098, 0.40102814, 0.53250168, 0.73020593,
         0.56360618, 0.30040046]],

       [[0.44695229, 0.74951402, 0.32471716, 0.97656525, 0.06957065,
         0.19834499, 0.83045755],
        [0.52164568, 0.79913131, 0.05868669, 0.02788667, 0.70122506,
         0.75106954, 0.45945085],
        [0.20182958, 0.51291772, 0.56279754, 0.2252648 , 0.73039794,
         0.11990629, 0.54484842]],

       [[0.67879477, 0.69734911, 0.42056657, 0.3503897 , 0.49120607

In [ ]:
y=np.array([2,4,9,7,6,1,9,0,4,7,3,5,3,7,5,1])
c=np.reshape(y,(2,8))
c

array([[2, 4, 9, 7, 6, 1, 9, 0],
       [4, 7, 3, 5, 3, 7, 5, 1]])

In [ ]:
t=np.arange(18)
t
r=np.reshape(t,(2,9))
r


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [ ]:
sc=np.array([22,5,74,6,9,22,90,12,6,78,5])
c=sc[4:7]
c

array([ 9, 22, 90])

In [ ]:
a=np.array([1,4,7])
b=np.array([8,5,7])
a+b

array([ 9,  9, 14])

In [ ]:
print(np.concatenate((a,b)))


[1 4 7 8 5 7]


In [ ]:
c=np.array([1,44,7,3,9,2,2,8,5,5])
print(np.unique(c))

[ 1  2  3  5  7  8  9 44]


In [ ]:
print(np.eye((5)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:

d=np.linspace(1,12,7)
print(d)

[ 1.          2.83333333  4.66666667  6.5         8.33333333 10.16666667
 12.        ]


In [ ]:
a=np.array([1,2,3,4,5,6,77])
mmax=np.argmax(a)
mmax


np.int64(6)

In [ ]:
print(np.argmin(a))

0


In [ ]:
print(np.where(a<4))

(array([0, 1, 2]),)


In [ ]:
print(np.where(a>4))

(array([4, 5, 6]),)


In [ ]:
print(np.cumsum(a))

[ 1  3  6 10 15 21 98]


In [ ]:
ran=np.random.randint(10,50,45)
ran

array([12, 10, 36, 18, 11, 34, 27, 32, 14, 29, 41, 28, 38, 26, 17, 19, 40,
       48, 13, 10, 21, 11, 37, 17, 45, 18, 21, 12, 22, 11, 28, 25, 23, 46,
       38, 31, 28, 10, 17, 37, 34, 36, 17, 37, 33])

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,4])
print(np.corrcoef(a,b))


[[ 1.         -0.16439899]
 [-0.16439899  1.        ]]


In [ ]:
n=np.save("num.npy",a)
print(np.load("num.npy"))

[1 2 3 4 5]


In [ ]:
c=np.array([2,3,4,5,6,7,8,9])
print(c[3:5])

[5 6]


In [ ]:
print(c[:6])

[2 3 4 5 6 7]


In [ ]:
print(c[::3])

[2 5 8]


In [ ]:
print(c[::-1])

[9 8 7 6 5 4 3 2]


In [ ]:
print(c[:-1])

[2 3 4 5 6 7 8]


In [ ]:
print(c[-5:-2])

[5 6 7]


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
print(arr[:,:3:3])


[[1]
 [5]
 [9]]


In [ ]:
print(arr[1:3,2:4])

[[7 8]
 [2 3]]


In [ ]:
import pandas as pd


In [ ]:
file=pd.read_csv("googleplaystore.csv")
file

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device


In [ ]:
import numpy as np


In [ ]:
sc=np.array([[11,67,93,80],[22,76,89,21],[22,55,97,64]])
print(sc[2:3,1:])

[[55 97 64]]


In [ ]:
print(sc[:,::2])

[[11 93]
 [22 89]
 [22 97]]


In [ ]:
print(sc[1:,:2])

[[22 76]
 [22 55]]
