In [3]:
import numpy as np


In [4]:
arr=np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,1,4,5]]])
arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 1, 4, 5]]])

In [5]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)


3
(1, 3, 4)
12
int64
8
96


In [6]:
array=np.array([1010.2,2010.3,3010.4,4010.5],dtype=np.float32)
print(array)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)

[1010.2 2010.3 3010.4 4010.5]
float32
4
16


In [7]:
array=np.array([1010.2,2010.3,3010.4,4010.5],dtype=np.float64)
print(array)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)


[1010.2 2010.3 3010.4 4010.5]
float64
8
32


In [8]:
array=np.array([1010.2,2010.3,3010.4,4010.5],dtype=np.int32)
print(array)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)

[1010 2010 3010 4010]
int32
4
16


In [10]:
mat=np.array([[
    [11,22,33,43,55],
    [66,76,88,99,10],
    [32,67,90,11,12],
    [66,67,84,23,10],
    [78,90,45,30,22],
    [45,65,75,85,95],
    [23,24,25,26,27],
    [90,80,70,50,40]]])



In [11]:
print(mat)
print(mat.shape)
print(mat.dtype)

[[[11 22 33 43 55]
  [66 76 88 99 10]
  [32 67 90 11 12]
  [66 67 84 23 10]
  [78 90 45 30 22]
  [45 65 75 85 95]
  [23 24 25 26 27]
  [90 80 70 50 40]]]
(1, 8, 5)
int64


In [12]:
linespace=np.linspace(0,1,4)
print(linespace)

[0.         0.33333333 0.66666667 1.        ]


In [19]:
arr=np.array([[[33,34,35,36,37],
               [38,39,40,41,42],
               [43,44,45,46,47],
               [48,49,50,51,52],
               [53,54,55,56,57],
               [30,31,32,10,16],

               ]])


In [26]:
print(arr[0,0])

[33 34 35 36 37]


In [28]:
print(arr[0:7:4,0:7:4])

[[[33 34 35 36 37]
  [53 54 55 56 57]]]


In [40]:
print(arr[2:4:1,2:6:1])

[]


In [55]:
array=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(array)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [56]:
print(array.reshape(5,2))


[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [58]:
print(array[0:2,0:2])

[[1 2]
 [6 7]]


In [64]:
print(array.T)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [68]:
salari=np.array([1000,2000,3000,4000,5000])
print(np.max(salari))
print(np.min(salari))


5000
1000


In [69]:
array=np.array([[
    [13,23,34,45],
    [21,22,33,44],
    [33,44,55,66],
    [55,66,77,88],
    [11,12,34,56],
    [56,77,58,59]
]])
array1=np.array([[
    [13,23,34,45],
    [21,22,33,44],
    [33,44,55,66],
    [55,66,77,88],
    [11,12,34,56],
    [56,77,58,59]
]])
print(array+array1)

[[[ 26  46  68  90]
  [ 42  44  66  88]
  [ 66  88 110 132]
  [110 132 154 176]
  [ 22  24  68 112]
  [112 154 116 118]]]


In [70]:
print(array*array1)

[[[ 169  529 1156 2025]
  [ 441  484 1089 1936]
  [1089 1936 3025 4356]
  [3025 4356 5929 7744]
  [ 121  144 1156 3136]
  [3136 5929 3364 3481]]]


In [71]:
print(array-array1)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [72]:
array/array1

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [74]:
array=np.array([[
    [13,23,34,45],
    [21,22,33,44],
    [33,44,55,66],
    [55,66,77,88],
    [11,12,34,56],
    [56,77,58,59]
]])
b=np.array([1,2,3,4])
print(array-b)

[[[12 21 31 41]
  [20 20 30 40]
  [32 42 52 62]
  [54 64 74 84]
  [10 10 31 52]
  [55 75 55 55]]]


In [75]:
value=np.array([99,-110,220,-230,240])
print(value)

[  99 -110  220 -230  240]


In [80]:
value[value>100]=0
print(value)


[  99 -110    0 -230    0]
